/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/cluster/home/zbinczyk/python"
#define EXEC_PREFIX "/cluster/home/zbinczyk/python"
#define BINDIR "/cluster/home/zbinczyk/python/bin"
#define SBINDIR "/cluster/home/zbinczyk/python/sbin"
#define LIBEXECDIR "/cluster/home/zbinczyk/python/libexec"
#define DATAROOTDIR "/cluster/home/zbinczyk/python/share"
#define DATADIR "/cluster/home/zbinczyk/python/share"
#define SYSCONFDIR "/cluster/home/zbinczyk/python/etc"
#define SHAREDSTATEDIR "/cluster/home/zbinczyk/python/com"
#define LOCALSTATEDIR "/cluster/home/zbinczyk/python/var"
#define RUNSTATEDIR "/cluster/home/zbinczyk/python/var/run"
#define INCLUDEDIR "/cluster/home/zbinczyk/python/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/cluster/home/zbinczyk/python/share/doc/m4"
#define INFODIR "/cluster/home/zbinczyk/python/share/info"
#define HTMLDIR "/cluster/home/zbinczyk/python/share/doc/m4"
#define DVIDIR "/cluster/home/zbinczyk/python/share/doc/m4"
#define PDFDIR "/cluster/home/zbinczyk/python/share/doc/m4"
#define PSDIR "/cluster/home/zbinczyk/python/share/doc/m4"
#define LIBDIR "/cluster/home/zbinczyk/python/lib"
#define LISPDIR "/cluster/home/zbinczyk/python/share/emacs/site-lisp"
#define LOCALEDIR "/cluster/home/zbinczyk/python/share/locale"
#define MANDIR "/cluster/home/zbinczyk/python/share/man"
#define PKGDATADIR "/cluster/home/zbinczyk/python/share/m4"
#define PKGINCLUDEDIR "/cluster/home/zbinczyk/python/include/m4"
#define PKGLIBDIR "/cluster/home/zbinczyk/python/lib/m4"
#define PKGLIBEXECDIR "/cluster/home/zbinczyk/python/libexec/m4"
